import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import { waitForCubismCore, acquireCubismFramework } from '../src/avatar/cubism/runtime.mjs';
import { createCubismParameterBridge, cubismParameterTargets } from '../src/avatar/cubism/parameters.mjs';

test('actual licensed SDK 5-r.5 Core initializes and the pinned Framework shares its native runtime', async () => {
  const source = await fs.readFile(new URL('../public/vendor/live2d/live2dcubismcore.min.js', import.meta.url), 'utf8');
  const sandbox = { console, setTimeout, clearTimeout, TextDecoder, TextEncoder, atob, btoa, window: {}, document: { currentScript: { src: 'https://petpal.test/vendor/live2d/live2dcubismcore.min.js' } } };
  vm.runInNewContext(source, sandbox, { timeout: 2000, filename: 'licensed-live2dcubismcore.min.js' });
  const core = await waitForCubismCore(() => sandbox.Live2DCubismCore);
  assert.equal(core.Version.csmGetVersion(), 0x06000001);
  assert.equal(core.Version.csmGetLatestMocVersion(), 6);
  globalThis.Live2DCubismCore = core;
  const framework = await import('../public/avatars/cubism-runtime/framework.mjs');
  const one = acquireCubismFramework(framework, core), two = acquireCubismFramework(framework, core);
  assert.equal(framework.CubismFramework.isInitialized(), true);
  const shaders = framework.CubismShaderManager_WebGL.getInstance(), glOne = {}, glTwo = {};
  shaders.setGlContext(glOne); shaders.setGlContext(glTwo);
  const secondShader = shaders.getShader(glTwo);
  framework.releaseCubismContext(glOne);
  assert.equal(shaders.getShader(glOne), undefined);
  assert.equal(shaders.getShader(glTwo), secondShader);
  framework.releaseCubismContext(glTwo);
  // Native model acceptance is separate from the browser/texture/render acceptance.
  const bytes = await fs.readFile(new URL('../public/avatars/akari-cubism/akari.moc3', import.meta.url));
  const mocBytes = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
  assert.equal(core.Version.csmGetMocVersion(mocBytes), 5);
  assert.equal(framework.CubismMoc.hasMocConsistency(mocBytes), true);
  const avatar = new framework.CubismUserModel(); avatar.loadModel(mocBytes, true);
  const model = avatar.getModel(); assert.ok(model.getDrawableCount() > 0);
  const settingBytes = await fs.readFile(new URL('../public/avatars/akari-cubism/akari.model3.json', import.meta.url));
  const settingBuffer = settingBytes.buffer.slice(settingBytes.byteOffset, settingBytes.byteOffset + settingBytes.byteLength);
  const setting = new framework.CubismModelSettingJson(settingBuffer, settingBuffer.byteLength);
  const motionBytes = await fs.readFile(new URL('../public/avatars/akari-cubism/akari.idle.motion3.json', import.meta.url));
  const motionBuffer = motionBytes.buffer.slice(motionBytes.byteOffset, motionBytes.byteOffset + motionBytes.byteLength);
  const motion = avatar.loadMotion(motionBuffer, motionBuffer.byteLength, 'Idle_0', undefined, undefined, setting, 'Idle', 0, true);
  motion.setEffectIds(Array.from({ length: setting.getEyeBlinkParameterCount() }, (_, index) => setting.getEyeBlinkParameterId(index)), Array.from({ length: setting.getLipSyncParameterCount() }, (_, index) => setting.getLipSyncParameterId(index)));
  avatar._motionManager.startMotionPriority(motion, false, 1);
  model.loadParameters(); avatar._motionManager.updateMotion(model, .1); model.saveParameters(); model.update();
  const bridge = createCubismParameterBridge(model, framework.CubismFramework.getIdManager());
  assert.ok(bridge.supported.includes('ParamMouthOpenY'));
  bridge.apply(cubismParameterTargets({ speaking: true, mouthOpen: .8 }), { mouthOnly: true }); model.update();
  const mouth = model.getParameterIndex(framework.CubismFramework.getIdManager().getId('ParamMouthOpenY'));
  assert.ok(Math.abs(model.getParameterValueByIndex(mouth) - .8) < .0001);
  bridge.apply(cubismParameterTargets({ speaking: false, mouthOpen: .8 }), { mouthOnly: true }); model.update();
  assert.equal(model.getParameterValueByIndex(mouth), 0);
  avatar.release();
  one.release(); assert.equal(framework.CubismFramework.isInitialized(), true);
  two.release(); assert.equal(framework.CubismFramework.isInitialized(), false);
  delete globalThis.Live2DCubismCore;
});
