import { listenFixture } from './helpers/loopback.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createPetServer } from '../server/app.mjs';
import { JsonStore } from '../server/store.mjs';
import { defaultCodexConfig } from '../server/codex-config.mjs';

test('HTTP relay keeps central key private, enforces run/model credentials and expires on completion',async t=>{
  const directory=await mkdtemp(path.join(tmpdir(),'petpal-executor-relay-'));
  const store=await new JsonStore(directory).init();store.state.codexConfig={...defaultCodexConfig(),mode:'api',baseUrl:'https://fixed-upstream.example/v1',model:'authorized-model',apiKey:'fixture-central-private-key'};await store.save();
  const upstream=[],output='event: response.completed\ndata: {"type":"response.completed","response":{"id":"response-fixture","status":"completed","output":[]}}\n\n';
  let upstreamOutput=output;
  const server=await createPetServer({dataDir:directory,token:'fixture-owner-session',codex:{async status(){return {available:true,authenticated:true};},async close(){},run(){throw new Error('central must not execute');}},executorsOptions:{pollMs:5,stopMs:20,fetchImpl:async(url,init)=>{upstream.push({url,init});return new Response(upstreamOutput,{headers:{'Content-Type':'text/event-stream'}});}}});
  await listenFixture(server.server);const origin=`http://127.0.0.1:${server.server.address().port}`;
  t.after(async()=>{await server.close();assert.ok(directory.startsWith(path.join(tmpdir(),'petpal-executor-relay-')));await rm(directory,{recursive:true,force:true});});
  const request=async(route,{method='GET',body,token='fixture-owner-session'}={})=>{const response=await fetch(origin+'/api'+route,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,body:await response.json()};};
  const registration=await request('/agent/executors/register',{method:'POST',body:{deviceId:randomUUID(),name:'Relay PC',platform:'win32',arch:'x64'}});assert.equal(registration.status,200);
  const {hostId,connectionId}=registration.body;
  const chat=(await request('/conversations',{method:'POST',body:{mode:'codex'}})).body;
  const submission=await request(`/conversations/${chat.id}/agent/submit`,{method:'POST',body:{submissionId:randomUUID(),hostId,content:'run fixture'}});assert.equal(submission.status,200);
  const command=(await request(`/agent/executors/${connectionId}/poll`)).body.commands[0];assert.equal(command.type,'run');assert.doesNotMatch(JSON.stringify(command),/fixture-central-private-key|fixed-upstream/);
  const events=`/agent/executors/${connectionId}/events`,relay=`/agent/executors/${connectionId}/runs/${command.runId}/model/responses`;
  assert.equal((await request(events,{method:'POST',body:{runId:command.runId,sequence:1,event:'started',data:{}}})).status,200);
  assert.equal((await request('/state',{token:command.relayToken})).status,401);
  assert.equal((await request(relay,{method:'POST',body:{model:'authorized-model',stream:true}})).status,401);
  assert.equal((await request(relay,{method:'POST',token:command.relayToken,body:{model:'unassigned-model',stream:true}})).status,400);
  assert.equal((await request(relay.replace(command.runId,randomUUID()),{method:'POST',token:command.relayToken,body:{model:'authorized-model',stream:true}})).status,401);
  assert.equal(upstream.length,0);
  const response=await fetch(origin+'/api'+relay,{method:'POST',headers:{Authorization:`Bearer ${command.relayToken}`,'Content-Type':'application/json'},body:JSON.stringify({model:'authorized-model',stream:true,input:'hello'})});
  assert.equal(response.status,200);assert.equal(await response.text(),output);assert.equal(upstream.length,1);
  assert.equal(upstream[0].url,'https://fixed-upstream.example/v1/responses');assert.equal(upstream[0].init.headers.Authorization,'Bearer fixture-central-private-key');assert.equal(upstream[0].init.redirect,'manual');
  const encode=value=>`event: ${value.type}\ndata: ${JSON.stringify(value)}\n\n`;
  upstreamOutput=[{type:'response.output_text.delta',item_id:'message-fixture',output_index:0,content_index:0,delta:'fixture-central-'},{type:'response.output_text.delta',item_id:'message-fixture',output_index:0,content_index:0,delta:'private-key'},{type:'response.output_text.done',item_id:'message-fixture',output_index:0,content_index:0,text:'fixture-central-private-key'},{type:'response.completed',response:{id:'response-fixture',status:'completed',output:[]}}].map(encode).join('');
  const protectedResponse=await fetch(origin+'/api'+relay,{method:'POST',headers:{Authorization:`Bearer ${command.relayToken}`,'Content-Type':'application/json'},body:JSON.stringify({model:'authorized-model',stream:true,input:'credential echo fixture'})});
  assert.equal(protectedResponse.status,200);const wire=await protectedResponse.text();assert.doesNotMatch(wire,/fixture-central-private-key/);
  const deltas=wire.split('\n').filter(line=>line.startsWith('data: ')).map(line=>JSON.parse(line.slice(6))).filter(frame=>frame.type==='response.output_text.delta').map(frame=>frame.delta).join('');assert.equal(deltas,'[已隐藏]');
  assert.equal((await request(events,{method:'POST',body:{runId:command.runId,sequence:2,event:'complete',data:{threadId:'thread-fixture',text:'done'}}})).status,200);
  assert.equal((await request(relay,{method:'POST',token:command.relayToken,body:{model:'authorized-model',stream:true}})).status,401);
  const legacy=await request(`/conversations/${chat.id}/messages`,{method:'POST',body:{content:'must not fall back to central'}});assert.equal(legacy.status,409);
  assert.doesNotMatch(JSON.stringify((await request('/agent/hosts')).body),/fixture-central-private-key|relayToken|sessionHash/);
});
