#!/usr/bin/env node
// Offline release preparation. This module never fetches, uploads or invokes gh.
import { createHash, createPrivateKey, createPublicKey, generateKeyPairSync, sign } from 'node:crypto';
import { lstat, mkdir, open, unlink } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { parseStableVersion, validateUpdateRepository, validateGitHubAssetUrl, verifyUpdateEnvelope, UPDATE_FILE_LIMIT, UPDATE_MANIFEST_LIMIT } from '../server/updates.mjs';
import { validateServerManifestUrl, validateServerAssetUrl } from '../server/update-source.mjs';

const FORMATS = Object.freeze({ 'windows-x64': ['portable-exe', '.exe'], 'ubuntu-x64': ['tar.gz', '.tar.gz'], 'ubuntu-arm64': ['tar.gz', '.tar.gz'], android: ['apk', '.apk'], web: ['web-zip', '.zip'] });
const record = value => value && typeof value === 'object' && !Array.isArray(value);
const fields = (value, allowed) => record(value) && Object.keys(value).every(key => allowed.includes(key));
const usage = `离线签名更新清单工具（GitHub Releases / 服务器，Node.js 22+）
  node scripts/sign-update.mjs keygen --out-dir .release-private
  node scripts/sign-update.mjs sign --config docs/update-release.example.json --key .release-private/update-private.pem --out releases/petpal-update.json
keygen 需要显式目录，已有密钥或已有输出均不会覆盖。私钥内容不会输出。`;

async function absent(file) {
  try { await lstat(file); } catch (error) { if (error.code === 'ENOENT') return; throw error; }
  throw new Error('输出已存在；请使用新的路径，不会覆盖已有文件。');
}

async function readSmall(file, maximum, label) {
  const before = await lstat(file);
  if (!before.isFile() || before.isSymbolicLink() || before.size < 1 || before.size > maximum) throw new Error(`${label}必须是有界的普通文件，不能是符号链接。`);
  const handle = await open(file, 'r');
  try {
    const opened = await handle.stat();
    if (!opened.isFile() || opened.size !== before.size || opened.ino !== before.ino || opened.dev !== before.dev) throw new Error(`${label}读取前发生变化。`);
    const chunks = []; let length = 0;
    for await (const chunk of handle.createReadStream({ autoClose: false })) {
      length += chunk.length;
      if (length > maximum) throw new Error(`${label}过大。`);
      chunks.push(chunk);
    }
    const after = await handle.stat();
    if (after.size !== before.size || after.mtimeMs !== before.mtimeMs || after.ctimeMs !== before.ctimeMs || length !== before.size) throw new Error(`${label}读取时发生变化。`);
    return Buffer.concat(chunks, length);
  } finally { await handle.close(); }
}

/** Explicit invocation only. No project key is generated by imports or tests. */
export async function generateUpdateKeys(directory) {
  if (typeof directory !== 'string' || !directory.trim()) throw new Error('keygen 必须显式提供 --out-dir；建议使用 .release-private/。');
  const output = path.resolve(directory), privateFile = path.join(output, 'update-private.pem'), publicFile = path.join(output, 'update-public.pem');
  await absent(privateFile); await absent(publicFile);
  await mkdir(output, { recursive: true, mode: 0o700 });
  if ((await lstat(output)).isSymbolicLink()) throw new Error('密钥输出目录不能是符号链接。');
  let privateHandle, publicHandle, complete = false;
  try {
    privateHandle = await open(privateFile, 'wx', 0o600);
    publicHandle = await open(publicFile, 'wx', 0o644);
    const keys = generateKeyPairSync('ed25519');
    await privateHandle.writeFile(keys.privateKey.export({ type: 'pkcs8', format: 'pem' }));
    await publicHandle.writeFile(keys.publicKey.export({ type: 'spki', format: 'pem' }));
    await privateHandle.sync(); await publicHandle.sync();
    complete = true;
    return { publicKeyPath: publicFile };
  } finally {
    await Promise.allSettled([privateHandle?.close(), publicHandle?.close()]);
    if (!complete) {
      if (privateHandle) await unlink(privateFile).catch(() => {});
      if (publicHandle) await unlink(publicFile).catch(() => {});
    }
  }
}

function validateConfig(config, now) {
  if (!fields(config, ['source', 'manifestUrl', 'repository', 'tag', 'sequence', 'expiresAt', 'artifacts'])) throw new Error('发布配置字段无效。');
  const source = config.source ?? 'github';
  if (!['github', 'server'].includes(source)) throw new Error('发布来源必须为 github 或 server。');
  const repository = validateUpdateRepository(config.repository ?? (source === 'server' ? 'lixinyu02/petpal' : undefined));
  const manifestUrl = source === 'server' ? validateServerManifestUrl(config.manifestUrl) : '';
  if (source === 'github' && (typeof config.tag !== 'string' || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(config.tag))) throw new Error('tag 必须是单段 GitHub 发布标签，例如 v0.6.0。');
  if (source === 'github' && config.manifestUrl) throw new Error('GitHub 发布配置不能包含服务器清单地址。');
  if (!Number.isSafeInteger(config.sequence) || config.sequence < 1) throw new Error('sequence 必须是递增的正安全整数。');
  if (typeof config.expiresAt !== 'string' || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(config.expiresAt) || !Number.isFinite(Date.parse(config.expiresAt)) || Date.parse(config.expiresAt) <= now) throw new Error('expiresAt 必须是未来的 UTC ISO 时间。');
  if (!Array.isArray(config.artifacts) || !config.artifacts.length || config.artifacts.length > 5) throw new Error('artifacts 必须包含 1 到 5 个平台文件。');
  const targets = new Set(), names = new Set();
  for (const item of config.artifacts) {
    if (!fields(item, ['target', 'file', 'version', 'versionCode', 'notes']) || typeof item.target !== 'string' || !Object.hasOwn(FORMATS, item.target) || targets.has(item.target)) throw new Error('发布平台无效或重复。');
    targets.add(item.target); parseStableVersion(item.version);
    if (typeof item.file !== 'string' || !item.file || item.file.length > 4096 || /[\x00-\x1f\x7f]/.test(item.file)) throw new Error('发布文件路径无效。');
    const name = path.basename(item.file);
    if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,199}$/.test(name) || !name.toLowerCase().endsWith(FORMATS[item.target][1]) || names.has(name.toLowerCase())) throw new Error('安装包文件名必须唯一、扩展名匹配平台，并仅使用英文字母、数字、点、横线和下划线。');
    names.add(name.toLowerCase());
    if (item.notes !== undefined && (typeof item.notes !== 'string' || item.notes.length > 16000 || /[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(item.notes))) throw new Error('更新说明必须是 16000 字符以内的纯文本。');
    if (item.target === 'android' ? (!Number.isInteger(item.versionCode) || item.versionCode < 1 || item.versionCode > 2100000000) : item.versionCode !== undefined) throw new Error('Android 必须指定有效 versionCode；其他平台不能指定 versionCode。');
  }
  return { repository, source, manifestUrl };
}

async function hashArtifact(file) {
  const before = await lstat(file);
  if (!before.isFile() || before.isSymbolicLink() || before.size < 1 || before.size > UPDATE_FILE_LIMIT) throw new Error('发布文件必须是 1 byte 至 2 GiB 的普通文件，不能是目录或符号链接。');
  const handle = await open(file, 'r');
  try {
    const opened = await handle.stat();
    if (!opened.isFile() || opened.size !== before.size || opened.ino !== before.ino || opened.dev !== before.dev) throw new Error('发布文件读取前发生变化。');
    const hash = createHash('sha256'); let bytes = 0;
    for await (const chunk of handle.createReadStream({ autoClose: false })) {
      bytes += chunk.length;
      if (bytes > before.size || bytes > UPDATE_FILE_LIMIT) throw new Error('发布文件读取时增大或超过 2 GiB。');
      hash.update(chunk);
    }
    const after = await handle.stat(), named = await lstat(file);
    if (bytes !== before.size || after.size !== before.size || after.mtimeMs !== before.mtimeMs || after.ctimeMs !== before.ctimeMs || named.ino !== before.ino || named.dev !== before.dev || named.isSymbolicLink()) throw new Error('发布文件读取时发生变化，请冻结安装包后重试。');
    return { bytes, sha256: hash.digest('hex') };
  } finally { await handle.close(); }
}

export async function signUpdateManifest({ configFile, keyFile, outputFile, now } = {}) {
  if (![configFile, keyFile, outputFile].every(value => typeof value === 'string' && value.trim())) throw new Error('sign 必须指定 --config、--key 和 --out。');
  const issuedTime = now ?? Date.now();
  if (!Number.isFinite(issuedTime)) throw new Error('签名时间无效。');
  const configPath = path.resolve(configFile), outputPath = path.resolve(outputFile);
  await absent(outputPath);
  let config;
  try { config = JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(await readSmall(configPath, UPDATE_MANIFEST_LIMIT, '发布配置'))); }
  catch { throw new Error('无法读取发布配置，请提供 128 KiB 以内的 UTF-8 JSON 普通文件。'); }
  const {repository,source,manifestUrl} = validateConfig(config, issuedTime);
  let privateKey;
  try {
    privateKey = createPrivateKey(await readSmall(path.resolve(keyFile), 16 * 1024, '发布私钥'));
    if (privateKey.asymmetricKeyType !== 'ed25519') throw new Error('Wrong algorithm');
  } catch { throw new Error('无法读取 Ed25519 私钥；请使用 keygen 生成的 PKCS#8 PEM 文件。'); }
  const publicKey = createPublicKey(privateKey).export({ type: 'spki', format: 'pem' }).toString();
  const releases = [];
  for (const item of config.artifacts) {
    const file = path.resolve(path.dirname(configPath), item.file);
    const metadata = await hashArtifact(file);
    const url = source === 'server'
      ? validateServerAssetUrl(new URL(path.basename(file), manifestUrl).href, manifestUrl)
      : validateGitHubAssetUrl(`https://github.com/${repository}/releases/download/${encodeURIComponent(config.tag)}/${encodeURIComponent(path.basename(file))}`, repository);
    releases.push({ id: `${item.target}-${item.version}`, target: item.target, version: item.version, ...(item.versionCode !== undefined ? { versionCode: item.versionCode } : {}), url, ...metadata, notes: item.notes ?? '', format: FORMATS[item.target][0] });
  }
  const payload = { product: 'petpal', channel: 'stable', sequence: config.sequence, issuedAt: new Date(issuedTime).toISOString(), expiresAt: config.expiresAt, releases };
  const payloadBytes = Buffer.from(JSON.stringify(payload));
  const envelope = { schemaVersion: 1, payload: payloadBytes.toString('base64url'), signature: sign(null, payloadBytes, privateKey).toString('base64url') };
  const contents = Buffer.from(`${JSON.stringify(envelope, null, 2)}\n`);
  const verified = verifyUpdateEnvelope(contents, { repository, source, manifestUrl, publicKey, now: now ?? Date.now() });
  await mkdir(path.dirname(outputPath), { recursive: true });
  let handle, complete = false;
  try {
    handle = await open(outputPath, 'wx', 0o644);
    await handle.writeFile(contents); await handle.sync(); complete = true;
  } finally { await handle?.close(); if (handle && !complete) await unlink(outputPath).catch(() => {}); }
  return { outputPath, repository, source, ...(source === 'server' ? {manifestUrl} : {}), sequence: verified.sequence, releases: releases.length, bytes: contents.length, sha256: createHash('sha256').update(contents).digest('hex'), publicKeyFingerprint: verified.keyFingerprint };
}

export async function main(args = process.argv.slice(2)) {
  if (args.length === 0 || (args.length === 1 && ['--help', '-h', 'help'].includes(args[0]))) { console.log(usage); return; }
  const [command, ...rest] = args, allowed = command === 'keygen' ? ['--out-dir'] : command === 'sign' ? ['--config', '--key', '--out'] : [];
  if (!allowed.length) throw new Error('未知命令；使用 --help 查看用法。');
  const values = {};
  for (let index = 0; index < rest.length; index += 2) {
    const name = rest[index], value = rest[index + 1];
    if (!allowed.includes(name) || Object.hasOwn(values, name) || typeof value !== 'string' || !value || value.startsWith('--')) throw new Error('命令行参数缺失、重复或不受支持。');
    values[name] = value;
  }
  if (allowed.some(name => !Object.hasOwn(values, name))) throw new Error('缺少必需的显式文件参数；使用 --help 查看用法。');
  if (command === 'keygen') {
    const result = await generateUpdateKeys(values['--out-dir']);
    console.log(`发布公钥：${result.publicKeyPath}`);
  } else {
    const result = await signUpdateManifest({ configFile: values['--config'], keyFile: values['--key'], outputFile: values['--out'] });
    console.log(JSON.stringify(result, null, 2));
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  main().catch(error => { console.error(`发布工具失败：${error.message}`); process.exitCode = 1; });
}
