import {useEffect,useRef,useState,type FormEvent,type KeyboardEvent} from 'react';
import {CalendarClock,Check,ChevronDown,Clock,Loader2,Monitor,Pause,Pencil,Play,Plus,RefreshCw,Trash2,X} from 'lucide-react';
import {api,getSessionEpoch,isSessionChanged,type AgentHost,type Automation,type AutomationCatalog,type AutomationRun,type AutomationSchedule,type AgentPermissions as Permissions,type Provider,type User} from './api';
import {ExecutionHostPicker,ModelPicker} from './WorkspaceControls';
import AgentPermissions,{defaultAgentPermissions} from './AgentPermissions';
import {projectDirectoryIssue} from './project-directory-preferences.mjs';
import './automations.css';

type Preset='once'|'daily'|'weekdays'|'weekly'|'interval';
type Editor={id?:string;revision?:string;title:string;prompt:string;hostId:string;providerId:string;projectDirectory:string;permissions:Permissions;preset:Preset;at:string;time:string;timezone:string;weekdays:number[];minutes:string;enabled:boolean};
type Mutation={kind:'save'|'run'|'toggle'|'delete'|'preference'|'acknowledge';path:string;method:string;body:Record<string,unknown>;jobId?:string};
type Confirmation={kind:'cancel'}|{kind:'reload';job:Automation}|{kind:'ack';job:Automation;run:AutomationRun};
type Props={user?:User;providers:Provider[];reviewProviders?:Provider[];hosts:AgentHost[];localHostId?:string;defaultHostId?:string;hostsLoading?:boolean;hostsError?:string;onRefreshHosts?():void;onOpenConversation(id:string):void|Promise<void>;onEditingChange(value:{dirty:boolean;busy:boolean}):void};
const runLabels:Record<AutomationRun['status'],string>={claiming:'准备派发',queued:'排队中',running:'执行中',completed:'已完成',error:'执行失败',skipped:'已跳过',unknown:'状态待确认',cancelled:'已取消'};
const weekdayNames=['日','一','二','三','四','五','六'];
const date=(value?:string|null)=>{if(!value)return '暂无';const parsed=new Date(value);return Number.isFinite(parsed.getTime())?parsed.toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'时间无效';};
function localInput(value:string){const d=new Date(value);if(!Number.isFinite(d.getTime()))return '';return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;}
function scheduleLabel(s:AutomationSchedule){if(s.kind==='once')return `一次 · ${date(s.at)}`;if(s.kind==='interval')return `每 ${s.minutes} 分钟`;if(s.kind==='daily')return `每天 ${s.time} · ${s.timezone}`;return `每周${s.weekdays.map(day=>weekdayNames[day]).join('、')} ${s.time} · ${s.timezone}`;}
function newEditor(hostId:string,providerId:string):Editor{return {title:'',prompt:'',hostId,providerId,projectDirectory:'',permissions:{...defaultAgentPermissions},preset:'daily',at:'',time:'09:00',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Shanghai',weekdays:[1,2,3,4,5],minutes:'60',enabled:true};}
function editJob(job:Automation):Editor{const s=job.schedule;return {...newEditor(job.hostId,job.providerId||''),id:job.id,revision:job.revision,title:job.title,prompt:job.prompt,projectDirectory:job.projectDirectory||'',permissions:{...job.permissions},enabled:job.enabled,preset:s.kind==='weekly'&&s.weekdays.join(',')==='1,2,3,4,5'?'weekdays':s.kind,at:s.kind==='once'?localInput(s.at):'',time:'time' in s?s.time:'09:00',timezone:'timezone' in s?s.timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Shanghai',weekdays:s.kind==='weekly'?[...s.weekdays]:[1,2,3,4,5],minutes:s.kind==='interval'?String(s.minutes):'60'};}
function scheduleFrom(e:Editor):AutomationSchedule{if(e.preset==='once'){const at=new Date(e.at);if(!e.at||!Number.isFinite(at.getTime())||at.getTime()<=Date.now())throw Error('请选择未来的一次执行时间。');return {kind:'once',at:at.toISOString()};}if(e.preset==='interval'){const minutes=Number(e.minutes);if(!Number.isInteger(minutes)||minutes<5||minutes>10080)throw Error('执行间隔须为 5 至 10080 分钟的整数。');return {kind:'interval',minutes};}if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(e.time))throw Error('请选择有效的每日时间。');try{new Intl.DateTimeFormat('zh-CN',{timeZone:e.timezone});}catch{throw Error('请输入有效的 IANA 时区，例如 Asia/Shanghai。');}if(e.preset==='daily')return {kind:'daily',time:e.time,timezone:e.timezone};const weekdays=e.preset==='weekdays'?[1,2,3,4,5]:e.weekdays;if(!weekdays.length)throw Error('请至少选择一个星期。');return {kind:'weekly',time:e.time,timezone:e.timezone,weekdays:[...weekdays].sort()};}
function knownRejection(error:unknown){const status=(error as {status?:number})?.status;return typeof status==='number'&&status>=400&&status<500;}
function comparableSavedField(key:string,value:unknown){if(key!=='permissions'||!value||typeof value!=='object'||Array.isArray(value))return value;const permissions={...value as Record<string,unknown>};if(permissions.reviewProviderId==null||permissions.reviewProviderId==='')delete permissions.reviewProviderId;return permissions;}
function sameSaved(job:Automation,body:Record<string,unknown>){return Object.entries(body).filter(([key])=>!['revision','requestId'].includes(key)).every(([key,value])=>JSON.stringify(comparableSavedField(key,(job as unknown as Record<string,unknown>)[key]??(key==='projectDirectory'?'':undefined)))===JSON.stringify(comparableSavedField(key,value)));}

export default function AutomationsView({user,providers,reviewProviders=[],hosts,localHostId='',defaultHostId='',hostsLoading=false,hostsError='',onRefreshHosts,onOpenConversation,onEditingChange}:Props){
  const epoch=useRef(getSessionEpoch()).current,alive=useRef(true),loadSequence=useRef(0),mutationLock=useRef(false),callback=useRef(onEditingChange);callback.current=onEditingChange;
  const [catalog,setCatalog]=useState<AutomationCatalog>({allowAgentCreate:true,automations:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [editor,setEditor]=useState<Editor|null>(null),editorRef=useRef<Editor|null>(null),baseline=useRef('');
  const [pending,setPending]=useState(''),[uncertain,setUncertain]=useState<Mutation|null>(null),uncertainRef=useRef<Mutation|null>(null),[deleteId,setDeleteId]=useState(''),[opening,setOpening]=useState('');
  const [confirmation,setConfirmation]=useState<Confirmation|null>(null),confirmationRef=useRef<Confirmation|null>(null),confirmationElement=useRef<HTMLDivElement>(null),returnFocus=useRef<HTMLElement|null>(null),createButton=useRef<HTMLButtonElement>(null);
  const guard=useRef({dirty:false,busy:false}),catalogRef=useRef(catalog);catalogRef.current=catalog;
  const current=()=>alive.current&&epoch===getSessionEpoch();
  function editingState(dirty=guard.current.dirty,busy=guard.current.busy){guard.current={dirty,busy};callback.current(guard.current);}
  function changeEditor(next:Editor|null){editorRef.current=next;setEditor(next);editingState(!!next&&JSON.stringify(next)!==baseline.current);setError('');}
  function patchEditor(change:Partial<Editor>){if(!current()||mutationLock.current||uncertainRef.current||confirmationRef.current||!editorRef.current)return;changeEditor({...editorRef.current,...change});}
  function openEditor(job?:Automation){if(!current()||mutationLock.current||uncertainRef.current||confirmationRef.current||editorRef.current)return;const next=job?editJob(job):newEditor(defaultHostId||hosts[0]?.id||'',user?.isOwner?'':providers[0]?.id||'');baseline.current=JSON.stringify(next);changeEditor(next);setDeleteId('');}
  function askConfirmation(next:Confirmation){if(!current()||mutationLock.current||uncertainRef.current||confirmationRef.current)return;returnFocus.current=typeof document==='undefined'?null:document.activeElement as HTMLElement|null;confirmationRef.current=next;setConfirmation(next);editingState(true,false);}
  function closeConfirmation(){if(!current()||mutationLock.current||uncertainRef.current)return;confirmationRef.current=null;setConfirmation(null);editingState(!!editorRef.current&&JSON.stringify(editorRef.current)!==baseline.current);}
  function cancelEditor(){if(!current()||mutationLock.current||uncertainRef.current||confirmationRef.current)return;if(guard.current.dirty){askConfirmation({kind:'cancel'});return;}changeEditor(null);}
  function reloadEditor(job:Automation){if(guard.current.dirty){askConfirmation({kind:'reload',job});return;}const next=editJob(job);baseline.current=JSON.stringify(next);changeEditor(next);}
  function confirmAction(){const choice=confirmationRef.current;if(!current()||!choice||mutationLock.current||uncertainRef.current)return;confirmationRef.current=null;setConfirmation(null);if(choice.kind==='cancel')changeEditor(null);else if(choice.kind==='reload'){const next=editJob(choice.job);baseline.current=JSON.stringify(next);changeEditor(next);}else{editingState(false,false);void mutate({kind:'acknowledge',path:`/automations/${encodeURIComponent(choice.job.id)}/acknowledge`,method:'POST',body:{revision:choice.job.revision,runId:choice.run.id},jobId:choice.job.id});}}
  function confirmationKey(event:KeyboardEvent<HTMLDivElement>){if(event.key==='Escape'){event.preventDefault();event.stopPropagation();closeConfirmation();}else if(event.key==='Tab'){const buttons=Array.from(confirmationElement.current?.querySelectorAll<HTMLButtonElement>('button:not([disabled])')||[]);if(!buttons.length||typeof document==='undefined')return;const first=buttons[0],last=buttons[buttons.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}
  useEffect(()=>{if(confirmation){confirmationElement.current?.querySelector<HTMLButtonElement>('[data-confirm-cancel]')?.focus();}else{const target=returnFocus.current;returnFocus.current=null;if(target?.isConnected)target.focus();else if(target)createButton.current?.focus();}},[confirmation]);
  async function load(signal?:AbortSignal){if(!current()||signal?.aborted)return catalogRef.current;const sequence=++loadSequence.current;const result=await api<AutomationCatalog>('/automations',{signal});if(current()&&!signal?.aborted&&sequence===loadSequence.current){catalogRef.current=result;setCatalog(result);setLoading(false);}return result;}
  useEffect(()=>{alive.current=true;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;const poll=async()=>{try{if(!mutationLock.current&&!uncertainRef.current)await load(controller.signal);}catch(e){if(current()&&!controller.signal.aborted&&!isSessionChanged(e)){setError((e as Error).message);setLoading(false);}}finally{if(current()&&!controller.signal.aborted)timer=setTimeout(()=>void poll(),15000);}};editingState(false,false);void poll();return()=>{alive.current=false;loadSequence.current++;controller.abort();if(timer)clearTimeout(timer);callback.current({dirty:false,busy:false});};},[]);
  useEffect(()=>{if(!guard.current.dirty&&!guard.current.busy)return;const leave=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[editor,pending,uncertain,confirmation]);
  function acceptJob(job:Automation){const next={...catalogRef.current,automations:[job,...catalogRef.current.automations.filter(item=>item.id!==job.id)]};catalogRef.current=next;setCatalog(next);}
  async function mutate(request:Mutation,confirming=false){
    if(mutationLock.current||confirmationRef.current||(!confirming&&uncertainRef.current)||!current())return;
    mutationLock.current=true;loadSequence.current++;setPending(request.kind);setError('');setNotice('');editingState(guard.current.dirty,true);
    let unresolved=false;
    try{
      // An edit/delete may have committed before its acknowledgement was lost.
      // Read first; never repeat an optimistic write against a newer revision.
      if(confirming&&(['save','toggle','delete','preference'].includes(request.kind)&&request.method!=='POST'||request.kind==='acknowledge')){
        const snapshot=await api<AutomationCatalog>('/automations');if(!current())return;
        catalogRef.current=snapshot;setCatalog(snapshot);
        const job=snapshot.automations.find(item=>item.id===request.jobId);
        const applied=request.kind==='acknowledge'?!!job?.runs.some(run=>run.id===request.body.runId&&run.status==='cancelled'):request.kind==='delete'?!job:request.kind==='preference'?snapshot.allowAgentCreate===request.body.allowAgentCreate:!!job&&sameSaved(job,request.body);
        if(applied){uncertainRef.current=null;setUncertain(null);if(request.kind==='save')changeEditor(null);if(request.kind==='delete')setDeleteId('');setNotice('已确认此前的修改。');return;}
        if(job&&job.revision!==request.body.revision&&request.kind!=='preference'){uncertainRef.current=null;setUncertain(null);throw Object.assign(Error('计划已被其他窗口修改，请重新载入最新版本后编辑。'),{status:409});}
      }
      const result=await api<{automation?:Automation;run?:AutomationRun;allowAgentCreate?:boolean}>(request.path,{method:request.method,body:JSON.stringify(request.body)});if(!current())return;
      uncertainRef.current=null;setUncertain(null);
      if(result.automation)acceptJob(result.automation);
      if(request.kind==='save')changeEditor(null);
      if(request.kind==='preference'){const next={...catalogRef.current,allowAgentCreate:result.allowAgentCreate===true};catalogRef.current=next;setCatalog(next);}
      if(request.kind==='delete'){const next={...catalogRef.current,automations:catalogRef.current.automations.filter(item=>item.id!==request.jobId)};catalogRef.current=next;setCatalog(next);setDeleteId('');}
      if(request.kind==='run'&&result.run){const next={...catalogRef.current,automations:catalogRef.current.automations.map(job=>job.id===request.jobId?{...job,runs:[result.run!,...job.runs.filter(run=>run.id!==result.run!.id)].slice(0,30)}:job)};catalogRef.current=next;setCatalog(next);}
      setNotice(request.kind==='run'?'任务已提交，请在运行记录查看进度。':request.kind==='delete'?'自动化已删除。':request.kind==='acknowledge'?'已确认任务停止。计划仍暂停，需要时请另行恢复或立即执行。':'已保存。');
    }catch(e){if(!current()||isSessionChanged(e))return;if(knownRejection(e)){uncertainRef.current=null;setUncertain(null);setError((e as Error).message);if((e as {status?:number}).status===409)void load().catch(()=>{});}else{unresolved=true;uncertainRef.current=request;setUncertain(request);setError('未收到确定结果。请先确认原请求，避免重复创建或派发任务。');}}
    finally{mutationLock.current=false;if(current()){setPending('');editingState(guard.current.dirty,unresolved||!!uncertainRef.current);}}
  }
  function save(event:FormEvent){event.preventDefault();if(mutationLock.current||uncertainRef.current||confirmationRef.current||!editorRef.current||!user?.canUseCodex)return;const e=editorRef.current;try{if(!e.title.trim()||!e.prompt.trim())throw Error('请填写自动化名称和任务指令。');if(e.title.trim().length>120||e.prompt.trim().length>32000)throw Error('名称最多 120 字，指令最多 32000 字。');const host=hosts.find(item=>item.id===e.hostId);if(!host)throw Error('请选择已登记的执行电脑。');if(e.providerId&&!providers.some(item=>item.id===e.providerId)||!e.providerId&&!user.isOwner)throw Error('请选择账号可用的 Agent 模型。');const issue=projectDirectoryIssue(e.projectDirectory.trim(),host);if(issue)throw Error(issue);const body={title:e.title.trim(),prompt:e.prompt.trim(),hostId:e.hostId,providerId:e.providerId||null,projectDirectory:e.projectDirectory.trim(),permissions:e.permissions,schedule:scheduleFrom(e),enabled:e.enabled,...(e.id?{revision:e.revision}:{requestId:crypto.randomUUID()})};void mutate({kind:'save',path:e.id?`/automations/${encodeURIComponent(e.id)}`:'/automations',method:e.id?'PATCH':'POST',body,jobId:e.id});}catch(e){setError((e as Error).message);}}
  async function openConversation(id:string){if(!current()||mutationLock.current||uncertainRef.current||confirmationRef.current||editorRef.current||opening)return;setOpening(id);setError('');try{await onOpenConversation(id);}catch(e){if(current()&&!isSessionChanged(e))setError((e as Error).message);}finally{if(current())setOpening('');}}
  const disabled=!!pending||!!uncertain||!!confirmation,editing=!!editor,host=hosts.find(item=>item.id===editor?.hostId),jobs=catalog.automations;
  return <section className="automations-view" aria-label="自动化任务" aria-busy={loading||!!pending}>
    <div className="automations-heading"><div><span className="automations-eyebrow"><CalendarClock size={16} aria-hidden="true"/>让小伴按时帮忙</span><h1>自动化</h1><p>固定电脑，按计划执行。结果会保存在独立的运行记录中。</p></div><button type="button" className="primary-button" ref={createButton} disabled={disabled||editing||loading||!user?.canUseCodex||jobs.length>=50} onClick={()=>openEditor()}><Plus size={17} aria-hidden="true"/>新建自动化</button></div>
    {!user?.canUseCodex&&<p className="automations-feedback" role="status">你的账号尚未开通 Agent。请联系管理员分配权限后创建自动化。</p>}
    <div className="automations-preference"><label><input type="checkbox" checked={catalog.allowAgentCreate} disabled={disabled||loading||!user?.canUseCodex} onChange={event=>void mutate({kind:'preference',path:'/automations/preferences',method:'PATCH',body:{allowAgentCreate:event.target.checked}})}/><span>允许 Agent 创建自动化<small>继承当前任务的电脑、模型与权限；创建的计划会显示在这里。</small></span></label><button type="button" className="icon-button" aria-label="刷新自动化" disabled={disabled||loading} onClick={()=>void load().catch(e=>{if(current()&&!isSessionChanged(e))setError(e.message);})}><RefreshCw size={17} aria-hidden="true"/></button></div>
    {error&&<p className="automations-feedback is-error" role="alert">{error}</p>}{notice&&<p className="automations-feedback" role="status"><Check size={16} aria-hidden="true"/>{notice}</p>}
    {confirmation&&<div ref={confirmationElement} className="automation-inline-confirm" role="alertdialog" aria-modal={false} aria-labelledby="automation-confirm-title" aria-describedby="automation-confirm-description" tabIndex={-1} onKeyDown={confirmationKey}><h2 id="automation-confirm-title">{confirmation.kind==='ack'?'确认旧任务已经停止？':confirmation.kind==='reload'?'载入最新计划？':'放弃这次修改？'}</h2><p id="automation-confirm-description">{confirmation.kind==='ack'?`请先在“${confirmation.job.hostName||hosts.find(host=>host.id===confirmation.job.hostId)?.name||confirmation.job.hostId}”检查旧任务已经停止。确认只将此未知记录标为取消，计划仍暂停；以后需要另行恢复或立即执行。`:confirmation.kind==='reload'?'载入服务器上的最新版本会替换当前未保存的修改。':'当前自动化修改尚未保存。放弃后将关闭编辑器，对话草稿会保留。'}</p><div><button type="button" className="secondary-button" data-confirm-cancel disabled={!!pending||!!uncertain} onClick={closeConfirmation}>{confirmation.kind==='ack'?'保留待确认':'继续编辑'}</button><button type="button" className={confirmation.kind==='reload'?'primary-button':'danger-button'} disabled={!!pending||!!uncertain} onClick={confirmAction}>{confirmation.kind==='ack'?'确认已停止':confirmation.kind==='reload'?'载入最新版本':'放弃修改'}</button></div></div>}
    {uncertain&&<div className="automations-uncertain" role="status"><p>原请求已保留。确认会沿用相同请求标识与内容；若此前未送达，本次会完成提交。在结果确定前请保持此页面。</p><button type="button" className="secondary-button" disabled={!!pending} onClick={()=>void mutate(uncertain,true)}>{pending?<Loader2 size={15} className="spin" aria-hidden="true"/>:<RefreshCw size={15} aria-hidden="true"/>}确认结果</button></div>}
    {editor&&<form className="automation-editor" onSubmit={save} aria-label={editor.id?'编辑自动化':'新建自动化'}><div className="automation-editor-heading"><h2>{editor.id?'编辑自动化':'安排一件事'}</h2><button type="button" className="icon-button" aria-label="取消编辑" disabled={disabled} onClick={cancelEditor}><X size={18} aria-hidden="true"/></button></div>
      <label className="automation-field">名称<input aria-label="自动化名称" maxLength={120} value={editor.title} disabled={disabled} onChange={event=>patchEditor({title:event.target.value})} placeholder="例如：每天整理项目进展"/></label>
      <label className="automation-field">任务指令<textarea aria-label="任务指令" rows={3} maxLength={32000} value={editor.prompt} disabled={disabled} onChange={event=>patchEditor({prompt:event.target.value})} placeholder="描述希望 Agent 在这台电脑上完成的事"/></label>
      <div className="automation-editor-controls"><ExecutionHostPicker hosts={hosts} value={editor.hostId} onChange={hostId=>patchEditor({hostId,projectDirectory:''})} disabled={disabled} loading={hostsLoading} error={hostsError} localHostId={localHostId} onRefresh={onRefreshHosts} allowOffline/><ModelPicker providers={providers} value={editor.providerId} onChange={providerId=>patchEditor({providerId})} disabled={disabled} label="自动化模型" fallbackLabel="选择 Agent 模型" fallbackOption={user?.isOwner?{label:'主机默认配置'}:undefined}/><AgentPermissions reviewCapability={host?.codex?.approvalReview} reviewModel={providers.find(provider=>provider.id===editor.providerId)?.model||host?.codex?.model} reviewProviders={reviewProviders} value={editor.permissions} onChange={permissions=>patchEditor({permissions})} user={user} disabled={disabled}/></div>
      <label className="automation-field">项目目录<input aria-label="自动化项目目录" maxLength={4096} value={editor.projectDirectory} disabled={disabled||!host?.codex?.projectDirectory} onChange={event=>patchEditor({projectDirectory:event.target.value})} placeholder={host?.codex?.workspaceRoot||'留空使用默认工作区'} autoComplete="off" autoCorrect="off" autoCapitalize="off" spellCheck={false}/></label><button type="button" className="automation-reload" disabled={disabled||!editor.projectDirectory} onClick={()=>patchEditor({projectDirectory:''})}>使用默认工作区</button><p className="automation-help">目录属于所选电脑；执行前会检查路径。离线电脑可以保存计划，执行时须在线，不会转到其他电脑。</p>
      <div className="automation-schedule-fields"><label className="automation-field">何时执行<select aria-label="执行时间" value={editor.preset} disabled={disabled} onChange={event=>patchEditor({preset:event.target.value as Preset})}><option value="once">一次</option><option value="daily">每天</option><option value="weekdays">工作日</option><option value="weekly">每周</option><option value="interval">固定间隔</option></select></label>
      {editor.preset==='once'?<label className="automation-field">本地日期与时间<input type="datetime-local" aria-label="一次执行时间" value={editor.at} disabled={disabled} onChange={event=>patchEditor({at:event.target.value})}/></label>:editor.preset==='interval'?<label className="automation-field">间隔（分钟）<input type="number" min={5} max={10080} step={1} aria-label="每隔分钟" value={editor.minutes} disabled={disabled} onChange={event=>patchEditor({minutes:event.target.value})}/></label>:<><label className="automation-field">时间<input type="time" aria-label="每日时间" value={editor.time} disabled={disabled} onChange={event=>patchEditor({time:event.target.value})}/></label><label className="automation-field">时区<input aria-label="计划时区" value={editor.timezone} disabled={disabled} maxLength={100} onChange={event=>patchEditor({timezone:event.target.value})} placeholder="Asia/Shanghai"/></label></>}</div>
      {editor.preset==='weekly'&&<fieldset className="automation-weekdays"><legend>星期</legend>{weekdayNames.map((name,day)=><label key={day}><input type="checkbox" checked={editor.weekdays.includes(day)} disabled={disabled} onChange={event=>patchEditor({weekdays:event.target.checked?[...editor.weekdays,day].sort():editor.weekdays.filter(value=>value!==day)})}/><span>周{name}</span></label>)}</fieldset>}
      <p className="automation-help">服务器计算下一次执行时间。错过的计划不补跑，执行中的任务不会重叠；服务器和执行电脑须保持运行。</p>
      <div className="automation-editor-footer"><label className="automation-enabled"><input type="checkbox" checked={editor.enabled} disabled={disabled} onChange={event=>patchEditor({enabled:event.target.checked})}/>保存后启用</label><div><button type="button" className="secondary-button" disabled={disabled} onClick={cancelEditor}>取消编辑</button><button type="submit" className="primary-button" disabled={disabled||!user?.canUseCodex}>{pending==='save'&&<Loader2 size={15} className="spin" aria-hidden="true"/>}保存自动化</button></div></div>
      {editor.id&&jobs.find(job=>job.id===editor.id)?.revision!==editor.revision&&<button type="button" className="automation-reload" disabled={disabled} onClick={()=>{const job=jobs.find(item=>item.id===editor.id);if(job)reloadEditor(job);}}>重新载入最新版本</button>}
    </form>}
    {loading?<div className="automations-empty" role="status"><Loader2 className="spin" size={22} aria-hidden="true"/>正在读取你的计划…</div>:!jobs.length?<div className="automations-empty"><CalendarClock size={30} aria-hidden="true"/><h2>给想做的事安排时间</h2><p>从一项固定电脑上的小任务开始。你也可以在 Agent 对话中让小伴为它创建计划。</p></div>:<ol className="automation-list">{jobs.map(job=>{const runs=[...job.runs].sort((a,b)=>Date.parse(b.startedAt||b.scheduledFor)-Date.parse(a.startedAt||a.scheduledFor)),last=runs[0],unknown=job.runs.some(run=>run.status==='unknown'),running=job.runs.some(run=>['claiming','queued','running','unknown'].includes(run.status));return <li className={`automation-row${job.enabled?'':' is-paused'}`} key={job.id}><div className="automation-row-main"><span className="automation-row-icon"><CalendarClock size={21} aria-hidden="true"/></span><div className="automation-row-copy"><h2>{job.title}<span>{job.enabled?'已启用':'已暂停'}</span></h2><p><Clock size={13} aria-hidden="true"/>{scheduleLabel(job.schedule)}</p><p><Monitor size={13} aria-hidden="true"/>{job.hostName||hosts.find(host=>host.id===job.hostId)?.name||job.hostId}<span>· {job.providerName||providers.find(provider=>provider.id===job.providerId)?.name||(job.providerId?'原模型不可用':'主机默认配置')}</span></p><small>下次：{job.enabled?date(job.nextRunAt):'已暂停'}{last&&<> · 最近：{runLabels[last.status]}</>}</small></div><div className="automation-row-actions"><button type="button" className="icon-button" aria-label={`${job.enabled?'暂停':'恢复'}自动化：${job.title}`} disabled={disabled||editing||(!job.enabled&&unknown)} onClick={()=>void mutate({kind:'toggle',path:`/automations/${encodeURIComponent(job.id)}`,method:'PATCH',body:{revision:job.revision,enabled:!job.enabled},jobId:job.id})}>{job.enabled?<Pause size={17}/>:<Play size={17}/>}</button><button type="button" className="icon-button" aria-label={`编辑自动化：${job.title}`} disabled={disabled||editing} onClick={()=>openEditor(job)}><Pencil size={16}/></button><button type="button" className="icon-button" aria-label={`删除自动化：${job.title}`} disabled={disabled||editing} onClick={()=>setDeleteId(job.id)}><Trash2 size={16}/></button></div></div>
      <details className="automation-details"><summary>运行记录 <span>{job.runs.length}</span><ChevronDown size={15} aria-hidden="true"/></summary><div className="automation-detail-content"><p className="automation-prompt">{job.prompt}</p><p className="automation-help">{job.createdBy==='agent'?'由 Agent 创建':'由你创建'} · {date(job.createdAt)}{job.projectDirectory&&<> · 目录：{job.projectDirectory}</>}{job.sourceConversationId&&<button type="button" disabled={disabled||editing||!!opening} onClick={()=>void openConversation(job.sourceConversationId!)}>查看来源对话</button>}</p><button type="button" className="secondary-button" aria-label={`立即执行：${job.title}`} disabled={disabled||editing||running||!user?.canUseCodex||!hosts.some(host=>host.id===job.hostId&&host.online)} onClick={()=>void mutate({kind:'run',path:`/automations/${encodeURIComponent(job.id)}/run`,method:'POST',body:{requestId:crypto.randomUUID()},jobId:job.id})}><Play size={14} aria-hidden="true"/>立即执行</button>{!job.runs.length?<p className="automation-help">还没有运行记录。</p>:<>{unknown&&<p className="automation-help">旧任务状态不确定。请先在固定执行电脑上确认任务已停止，再确认记录；计划会继续暂停，不会自动重试。</p>}<ol className="automation-runs">{runs.map(run=><li key={run.id}><div><strong className={`automation-run-status status-${run.status}`}>{runLabels[run.status]}</strong><span>{date(run.startedAt||run.scheduledFor)} · {run.trigger==='manual'?'手动执行':'按计划执行'}</span>{run.message&&<p>{run.message}</p>}</div>{run.status==='unknown'&&<button type="button" disabled={disabled||editing} aria-label={`确认任务已停止：${job.title}`} onClick={()=>{askConfirmation({kind:'ack',job,run});}}>确认任务已停止</button>}{run.conversationId&&<button type="button" disabled={disabled||editing||!!opening} onClick={()=>void openConversation(run.conversationId!)}>{opening===run.conversationId?'正在打开…':'查看结果'}</button>}</li>)}</ol></>}</div></details>
      {deleteId===job.id&&<div className="automation-delete-confirm" role="alert"><p>删除“{job.title}”？计划及其未完成任务将取消，结果对话仍可保留。</p><div><button type="button" className="secondary-button" disabled={disabled} onClick={()=>setDeleteId('')}>保留计划</button><button type="button" className="danger-button" disabled={disabled} onClick={()=>void mutate({kind:'delete',path:`/automations/${encodeURIComponent(job.id)}`,method:'DELETE',body:{revision:job.revision},jobId:job.id})}>确认删除</button></div></div>}
    </li>;})}</ol>}
    <p className="automations-bottom-note">每个账号最多 50 项计划。运行记录保留最近 30 次；任务权限始终受账号授权限制。</p>
  </section>;
}
